version: "3"

services:         


    beer-service:
        image: priteela/beer-service
        networks:
            - sfg-brewery-network         
        ports: 
            - 8080:8080
        depends_on:
            - beer-service-db  
        deploy:
            replicas: 1   
            
            
    inventory-service:
        image: priteela/inventory-service
        networks:
            - sfg-brewery-network         
        ports: 
            - 8082:8082
        depends_on:
            - inventory-service-db  
        deploy:
            replicas: 1   
            
    order-service:
        image: priteela/order-service
        networks:
            - sfg-brewery-network         
        ports: 
            - 8081:8081
        depends_on:
            - order-service-db  
        deploy:
            replicas: 1   

    inventory-service-db:
        image: mysql:8.0
        networks:
            - sfg-brewery-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=beer_inventory_service
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=beerinventoryservice
        ports: 
             - "3308:3306"
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - c:/storage/docker/mysql/inventory-service-db:/var/lib/mysql            
                        
    beer-service-db:
        image: mysql:8.0
        networks:
            - sfg-brewery-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=beer_service
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=beerservice
        ports: 
             - "3307:3306"
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - c:/storage/docker/mysql/beer-service-db:/var/lib/mysql


    order-service-db:
        image: mysql:8.0
        networks:
            - sfg-brewery-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=beer_order_service
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=beerorderservice
        ports: 
             - "3309:3306"
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - c:/storage/docker/mysql/order-service-db:/var/lib/mysql
            
    artemis-jms-service:
        image: vromero/activemq-artemis
        networks:
            - sfg-brewery-network
        ports: 
             - "61616:61616"
             - "8161:8161"
           
networks:
    sfg-brewery-network: 